import type { Mesure } from './types'

/**
 * « À MESURER » — ce que le code laisse lire, JAMAIS peint. Une ligne ici devient une
 * brique le jour où on a LU la réponse (une mesure par ligne, commit à part).
 */
export const MESURES: Mesure[] = [
  {"id": "m-coffre-projecteur-chauffe", "titre": "Coffre : le projecteur redessiné à 20 Hz, à mesurer", "page": "coffre", "domaine": "eco", "lecture": "inconnu", "cout": "1 h", "note": "18-09, lecture du code (aucune mesure) : le faisceau sur la pièce (`Projecteur`, CoffreV2.swift:835-925) reconstruit 20 fois par seconde trois flous gaussiens plein cadre sous compositingGroup pour tourner une lumière de 13° — du GPU que la sonde ne voit pas, cohérent avec E76 (thermique 2, CPU bas). Et la Home ne dort pas sous le coffre, le chemin ni la fiche : ces trois fullScreenCover ne posent pas de couverture dans RythmeEcran.stories, contrairement aux stories. Le coffre n'a ni barreau ni SondeVol.tic. Posé l'après-midi (compilé, non mesuré, dessin intact) : `.couvreLaHome()` sur le coffre, le chemin, la fiche et le manège (RythmeEcran.couvertures, lu par dort) ; barreau `-sansProjecteur`, porte paused (arrière-plan, Reduce Motion, protection thermique) et tics[5] sur le projecteur. À mesurer sur son téléphone, thermique 0 : A/B -sansProjecteur (trajectoire thermique), tics[0..4] à 0 sous le coffre et sous le manège ; puis image cuite + Animatable sur t (montré avant de garder).", "preuve": {"fichier": "tools/perf/ANALYSE-COFFRE-CHAUFFE-2026-09-18.md"}},
  // 18-09 12:40 : « Re-mesurer barème cardio, faits et conversion après 083033 » est FAITE — les trois bancs
  // portés sur synchroniser_seance (faits sur compte jetable) : cardio 22 ✓, faits 14 ✓, coffre 53 ✓ ; notes sur
  // b-fn-pieces-cardio-seance, b-fn-calculer-faits, b-tb-coin-ledger (serveur.ts).
  {"id": "m-annonces-recus-durables", "titre": "Annonces durables : confirmer le parcours visuel", "page": "annonces", "domaine": "annonces", "lecture": "inconnu", "note": "Reçus, déduplication, acquittement et isolation déployés et vérifiés par API, branchés au Swift. Reste la séquence physique séance → story → toaster, puis reprise hors ligne ; vibration non confirmée.", "preuve": {"fichier": "tools/carte-lune/integration-2026-09-18/README.md"}},
  {"id": "m-cartes-noir-chevron-iphone", "titre": "Cartes sur iPhone : manège noir, chevron, coupure réseau", "page": "forge", "domaine": "forge", "lecture": "inconnu", "cout": "1 h", "note": "Ce que la passe iPhone du 18-09 16:38 n'a PAS couvert : le manège noir (0 sachet noir sur son compte — on n'en invente pas), la sortie par le chevron pendant que le manège tourne (elle a ouvert les deux sachets), une coupure réseau pendant l'ouverture, et l'endurance thermique (3 min à thermique 0 ne disent rien de 10). Se mesure quand un sachet noir aura été gagné pour de vrai.", "preuve": {"fichier": "tools/carte-lune/iphone-2026-09-18/README.md"}},
  {"id": "m-compte-historique-prod", "titre": "Historique iPhone rapproché, reconnexion à terminer", "page": "porte", "domaine": "compte", "lecture": "inconnu", "cout": "1 h", "note": "18-09, version76 : compte Apple9f5b775d confirmé par les préférences ;2séances finies locales/serveur, UUID et1série chacune concordants,0gain en file,2sachets et0carte. Pas38séances dans cette installation. Aucun effacement.76 précède le nouveau raccord ; reprise complète et reconnexion à mesurer sur77 après la chauffe.", "preuve": {"fichier": "tools/production/compte-iphone-2026-09-18/README.md"}},
  {"id":"m-cartes-shiny","titre":"Shiny : éveil animé et coût sur iPhone à vérifier","page":"forge","domaine":"forge","lecture":"inconnu","cout":"chantier","note":"18-09 : Kathryn demande une animation en plus des reflets des PNG. Illustration, poster et effet officiels partagés par référence ; réutiliser CarteVivante, arrêter hors écran et en arrière-plan, respecter Reduce Motion et protections thermiques. Aucun nouveau moteur shiny implémenté ou mesuré dans cette passe.","preuve":{"fichier":"tools/carte-lune/PLAN-CARTES-MONDES-2026-09-18.md"}},
  {"id": "m-cartes-qualite", "titre": "Trois familles : contraste final sur iPhone", "page": "forge", "domaine": "forge", "lecture": "inconnu", "note": "14 arts publiés, cadre réel exporté au simulateur. Nuit, marges, vignettes et reflets peints à confirmer sur écran physique. Nouveau shiny animé distinct et encore ouvert.", "preuve": {"fichier": "tools/carte-lune/integration-2026-09-18/README.md"}},
  {"id": "m-foyer-chauffe-longue", "titre": "Home noire animée : coût réduit, chauffe longue à vérifier", "page": "widgets", "domaine": "widgets", "lecture": "inconnu", "cout": "chantier", "note": "16-09, version42 installée et lancée après déverrouillage : comparaison dans le même binaire, tous les moteurs actifs, thermique0/protection0. Ancien rendu : CPU médian20 % sur31 lignes (t20,7–51,2) ; natif :3 % sur105 lignes (t90,4–195,9), puis3 % sur25 lignes au retour au natif. Cadence60,1 callbacks/s et pire17ms dans ces fenêtres. Fond, braises et silhouettes conservés ; interpolation confiée au compositeur et silhouettes mises en cache. Gain CPU mesuré, environ85 %, pas une mesure de watts. Endurance interrompue par un appel puis app inactive : chauffe longue encore ouverte. Prototype booster40 retiré faute de gain établi. ", "preuve": {"fichier": "tools/perf/campagnes/2026-09-16-retours-et-profil/etat.md"}},
  {"id": "m-home-voix-fr-en", "titre": "Confirmer les mots animés et l’haptique sur iPhone", "page": "widgets", "domaine": "widgets", "lecture": "inconnu", "cout": "chantier", "note": "16-09, retours 39/41 : une nouvelle variante courte à chaque arrivée réelle sur les deux Homes ; même phrasé flou que l’onboarding. Sur Home noire, compteur à la minute réelle et nouvelle formulation toutes les cinq minutes visibles. Aucun tirage ni réveil des minutes hors écran, aucun appel IA au geste. Rouge : 3 variantes aux retours, PASS 21,732 s ; noire : 3 variantes à trois minutes, PASS 27,896 s. Le texte reste présent même quand une protection coupe son animation. Haptique ressentie non confirmée. ", "preuve": {"fichier": "tools/perf/campagnes/2026-09-16-retours-et-profil/etat.md"}},
  // 15-09 (soir) : « Retirer le 20 en dur : pieces_par_serie vit au serveur » est FAITE et mesurée — devenue b-coffre-taux-serveur (briques.ts, page coffre).
  { id: "m-trancher-un-nud-un", titre: "Confirmer le choix : un galet par séance", page: "flow", domaine: "chemin", lecture: "inconnu", cout: "chantier", preuve: { fichier: "tools/road/AUDIT-CHEMIN-CALENDRIER-STORIES.md", lignes: "92-114" } , note: "18-09 : un galet par séance terminée avec travail implémenté et testé, y compris deux séances le même jour. Choix de travail annoncé ; préférence utilisateur contraire encore possible. Voir compte-progression-2026-09-18." },
  { id: "m-le-sticker-meme-choix", titre: "Le sticker : la même fonction aux deux écrans, sans source", page: "flow", domaine: "chemin", lecture: "inconnu", cout: "1 h", note: "Le sticker de la home/calendrier (HomeNuit.swift:1567) et du panneau de la route (DuolinguoPage.swift:2242) — aucune source serveur (colonne `workouts.sticker` absente, 400). C'est un sujet CHEMIN/CALENDRIER, pas story : il vivait sur la page histoire tant que la story dérivait, comme le sticker, de l'historique SwiftData. Depuis le 17-09 la story lit ses faits directement dans la clôture (b-st-top) — elle ne partage plus cette dérivation, donc ce chantier rejoint ses frères chemin sur la page flow.", preuve: { fichier: "tools/road/AUDIT-CHEMIN-CALENDRIER-STORIES.md", lignes: "69-86" } },
  { id: "m-definir-fait-parfait-et", "titre": "Après35 : calcul vérifié, rendu iPhone à qualifier", page: "flow", domaine: "chemin", lecture: "inconnu", cout: "1 j", "preuve": {"fichier": "tools/production/compte-progression-2026-09-18/README.md"} , "note": "18-09 : fait = séance terminée avec travail ; dernier galet accompli et daté, trésor final disponible.36e séance conservée sans remettre le chemin à zéro.1074 contrôles Swift et35API PASS. Aucun bonus « parfait » ajouté. Validation visuelle dans QA17." },
  { id: "m-cache-disque-des-png", titre: "Cache disque des PNG de cartes ; `depth_path` null partout", page: "forge", domaine: "forge", lecture: "inconnu", cout: "1 j", preuve: { fichier: "tools/sacre/SUPABASE-A-FAIRE.md", lignes: "56-60" } },
  { id: "m-fermer-la-sortie-par", titre: "Vérifier à l'écran que le chevron meurt à l'engagement", page: "forge", domaine: "forge", lecture: "inconnu", cout: "1 h", preuve: { aCiter: true } },
  {"id": "m-rattrapage-hors-ligne-du", "titre": "Coupure réseau : vérifier la reprise visuelle", "page": "forge", "domaine": "forge", "lecture": "inconnu", "note": "Opération persistante, attribution idempotente et reprise après2jours testées par API. L’app affiche attente/erreur et Réessayer ; dernier scénario de panne au milieu du geste sur iPhone encore ouvert.", "preuve": {"fichier": "tools/carte-lune/integration-2026-09-18/README.md"}},
  { id: "m-retirer-le-repli-jwtbanc", titre: "Retirer le repli `jwtBanc()` du chemin de production", page: "porte", domaine: "compte", lecture: "inconnu", cout: "1 h", preuve: { fichier: "Nosfy/Services/ForgeServeur.swift", lignes: "90-100" } },
  { id: "m-sortir-le-token-perso", titre: "Sortir le token perso du compte pro (`.secrets`)", page: "porte", domaine: "compte", lecture: "inconnu", cout: "1 h", preuve: { fichier: "tools/sacre/SUPABASE-A-FAIRE.md", lignes: "7-12" } },
  // 15-09 (suite) : « DecideurSerie → décideur à budget » (b-rg-rythme 🟢), « fermer forge-card sans booster_id »
  // (b-fo-serrure 🟢) et « valider le JWT dans weekly-synthesis » (bilan-periode vérifie le JWT) sont FAITES.
  // 15-09 : « policies d'écriture wallet / boosters », « vérifier les 4 migrations » et « réparer
  // schema_migrations » sont MESURÉES — devenues b-rls-argent-ferme et b-migrations-posees (serveur.ts).
]
