import type { Mesure } from './types'

/**
 * « À MESURER » — ce que le code laisse lire, JAMAIS peint. Une ligne ici devient une
 * brique le jour où on a LU la réponse (une mesure par ligne, commit à part).
 */
export const MESURES: Mesure[] = [
  {"id": "m-foyer-chauffe-longue", "titre": "Home noire animée : coût réduit, chauffe longue à vérifier", "page": "widgets", "domaine": "widgets", "lecture": "inconnu", "cout": "chantier", "note": "16-09, version42 installée et lancée après déverrouillage : comparaison dans le même binaire, tous les moteurs actifs, thermique0/protection0. Ancien rendu : CPU médian20 % sur31 lignes (t20,7–51,2) ; natif :3 % sur105 lignes (t90,4–195,9), puis3 % sur25 lignes au retour au natif. Cadence60,1 callbacks/s et pire17ms dans ces fenêtres. Fond, braises et silhouettes conservés ; interpolation confiée au compositeur et silhouettes mises en cache. Gain CPU mesuré, environ85 %, pas une mesure de watts. Endurance interrompue par un appel puis app inactive : chauffe longue encore ouverte. Prototype booster40 retiré faute de gain établi. ", "preuve": {"fichier": "tools/perf/campagnes/2026-09-16-retours-et-profil/etat.md"}},
  {"id": "m-home-voix-fr-en", "titre": "Confirmer les mots animés et l’haptique sur iPhone", "page": "widgets", "domaine": "widgets", "lecture": "inconnu", "cout": "chantier", "note": "16-09, retours 39/41 : une nouvelle variante courte à chaque arrivée réelle sur les deux Homes ; même phrasé flou que l’onboarding. Sur Home noire, compteur à la minute réelle et nouvelle formulation toutes les cinq minutes visibles. Aucun tirage ni réveil des minutes hors écran, aucun appel IA au geste. Rouge : 3 variantes aux retours, PASS 21,732 s ; noire : 3 variantes à trois minutes, PASS 27,896 s. Le texte reste présent même quand une protection coupe son animation. Haptique ressentie non confirmée. ", "preuve": {"fichier": "tools/perf/campagnes/2026-09-16-retours-et-profil/etat.md"}},
  // 15-09 (soir) : « Retirer le 20 en dur : pieces_par_serie vit au serveur » est FAITE et mesurée — devenue b-coffre-taux-serveur (briques.ts, page coffre).
  { id: "m-trancher-un-nud-un", titre: "Trancher « un nœud = un jour » vs « = une séance »", page: "flow", domaine: "chemin", lecture: "inconnu", cout: "chantier", preuve: { fichier: "tools/road/AUDIT-CHEMIN-CALENDRIER-STORIES.md", lignes: "92-114" } },
  { id: "m-le-sticker-meme-choix", titre: "Le sticker : la même fonction aux deux écrans, sans source", page: "flow", domaine: "chemin", lecture: "inconnu", cout: "1 h", note: "Le sticker de la home/calendrier (HomeNuit.swift:1567) et du panneau de la route (DuolinguoPage.swift:2242) — aucune source serveur (colonne `workouts.sticker` absente, 400). C'est un sujet CHEMIN/CALENDRIER, pas story : il vivait sur la page histoire tant que la story dérivait, comme le sticker, de l'historique SwiftData. Depuis le 17-09 la story lit ses faits directement dans la clôture (b-st-top) — elle ne partage plus cette dérivation, donc ce chantier rejoint ses frères chemin sur la page flow.", preuve: { fichier: "tools/road/AUDIT-CHEMIN-CALENDRIER-STORIES.md", lignes: "69-86" } },
  { id: "m-definir-fait-parfait-et", titre: "Définir « fait », « parfait », et l'après-35 séances", page: "flow", domaine: "chemin", lecture: "inconnu", cout: "1 j", preuve: { fichier: "docs/screens/duolingo-chemin.md", lignes: "416-432" } },
  { id: "m-passer-workout-id-a", titre: "Passer `workout_id` à `forge-card` (colonne toujours nulle)", page: "forge", domaine: "forge", lecture: "inconnu", cout: "1 h", preuve: { fichier: "Woop/Services/ForgeServeur.swift", lignes: "36" } },
  { id: "m-cache-disque-des-png", titre: "Cache disque des PNG de cartes ; `depth_path` null partout", page: "forge", domaine: "forge", lecture: "inconnu", cout: "1 j", preuve: { fichier: "tools/sacre/SUPABASE-A-FAIRE.md", lignes: "56-60" } },
  { id: "m-fermer-la-sortie-par", titre: "Vérifier à l'écran que le chevron meurt à l'engagement", page: "forge", domaine: "forge", lecture: "inconnu", cout: "1 h", preuve: { aCiter: true } },
  { id: "m-rattrapage-hors-ligne-du", titre: "Rattrapage hors-ligne du booster — l'outbox ignore la forge", page: "forge", domaine: "forge", lecture: "inconnu", cout: "1 j", preuve: { fichier: "Woop/Services/OutboxGains.swift", lignes: "42-51" } },
  { id: "m-retirer-le-repli-jwtbanc", titre: "Retirer le repli `jwtBanc()` du chemin de production", page: "porte", domaine: "compte", lecture: "inconnu", cout: "1 h", preuve: { fichier: "Woop/Services/ForgeServeur.swift", lignes: "90-100" } },
  { id: "m-sortir-le-token-perso", titre: "Sortir le token perso du compte pro (`.secrets`)", page: "porte", domaine: "compte", lecture: "inconnu", cout: "1 h", preuve: { fichier: "tools/sacre/SUPABASE-A-FAIRE.md", lignes: "7-12" } },
  // 15-09 (suite) : « DecideurSerie → décideur à budget » (b-rg-rythme 🟢), « fermer forge-card sans booster_id »
  // (b-fo-serrure 🟢) et « valider le JWT dans weekly-synthesis » (bilan-periode vérifie le JWT) sont FAITES.
  // 15-09 : « policies d'écriture wallet / boosters », « vérifier les 4 migrations » et « réparer
  // schema_migrations » sont MESURÉES — devenues b-rls-argent-ferme et b-migrations-posees (serveur.ts).
]
