import type { Brique } from './types'

/**
 * LA CARTE DU SERVEUR — tables, fonctions, règles, edge functions. Générée UNE fois par
 * tools/docsite/migrer.py depuis la v1, puis tenue À LA MAIN : changer un état ici, c'est
 * le changer partout. Chaque ligne a sa preuve ; « aCiter » est une dette visible.
 */
export const SERVEUR: Brique[] = [
  { id: "b-tb-coin-ledger", genre: "table", nom: "coin_ledger", titre: "coin_ledger", page: "serveur", domaine: "eco", etat: "ok", quoi: "Le carnet. Une ligne par gain ou dépense, jamais effacée ; le solde en est l'addition. Depuis le 30-08 soir un déclencheur (`coin_ledger_convertir`) convertit tout crédit jaune en sachets par tranches de 100 — une ligne -100 `conversion_booster` par sachet", preuve: { sonde: "GET /rest/v1/coin_ledger?raison=eq.conversion_booster&order=created_at.desc&limit=1 — 30-08 18:49 Paris, tools/annonces/verif_backend_coffre.py (TOUT EST VERT, 47 preuves), compte de test", reponse: "[{\"delta\":-100,\"booster_id\":\"a31cabff-…\",\"currency\":\"yellow\"}] — la raison existait depuis le 28-08, jamais écrite avant" } },
  { id: "b-tb-user-boosters", genre: "table", nom: "user_boosters", titre: "user_boosters", page: "serveur", domaine: "eco", etat: "ok", quoi: "Tes sachets. Une ligne par sachet gagné, converti ou tiré ; `opened_at` dit s'il est ouvert, `card_id` (30-08) scelle la carte forgée dessus ; origine `conversion` (30-08 soir) = né de 100 pièces", preuve: { sonde: "GET /rest/v1/user_boosters?origine=eq.conversion (count=exact) — 30-08 18:49 Paris, tools/annonces/verif_backend_coffre.py (TOUT EST VERT, 47 preuves), compte de test", reponse: "15 à la pose (le stock de 1 536 pièces), 16 après une clôture qui en convertit un" } },
  { id: "b-tb-reward-rules", genre: "table", nom: "reward_rules", titre: "reward_rules", page: "serveur", domaine: "eco", etat: "ok", quoi: "Les règles du jeu — 41 clés en base au 30-08 soir (40 mesurées + `fuseau_jour`) : prix, taux, budget d'annonces, géométrie et tirage du chemin, le fuseau du jour. Éditable à la main", preuve: { sonde: "GET /rest/v1/reward_rules?select=key (session) — 30-08 soir, relecture J0", reponse: "40 clés, puis fuseau_jour posée à 18:48" } },
  { id: "b-tb-workouts", genre: "table", nom: "workouts", titre: "workouts", page: "serveur", domaine: "sync", etat: "ok", quoi: "Tes séances, synchronisées depuis le téléphone", preuve: { fichier: "Woop/Services/SupabaseSync.swift", lignes: "113-116" } },
  { id: "b-tb-logged-exercises", genre: "table", nom: "logged_exercises", titre: "logged_exercises", page: "serveur", domaine: "sync", etat: "ok", quoi: "Les exercices d'une séance", preuve: { fichier: "Woop/Services/SupabaseSync.swift", lignes: "113-116" } },
  { id: "b-tb-strength-sets", genre: "table", nom: "strength_sets", titre: "strength_sets", page: "serveur", domaine: "sync", etat: "ok", quoi: "Les séries de muscu. Écrites depuis le 29-08 seulement — voir l'onglet 1", preuve: { fichier: "Woop/Services/SupabaseSync.swift", lignes: "113-116" } },
  { id: "b-tb-cardio", genre: "table", nom: "cardio_phases", titre: "`cardio_phases` existe et porte tout — mais elle est VIDE", page: "serveur", domaine: "sync", etat: "srv", quoi: "Les phases de cardio : `kind`, `seconds`, `speed`, `incline`, `cycle_index`, `position`. MESURÉ le 05-09 : la table existe avec ses six colonnes (témoin bidon → 400/42703, donc le 200 est une preuve) et `SupabaseSync.swift:117` y écrit à chaque séance — mais elle contient ZÉRO ligne", note: "le ⚪ « à retravailler » du 29-08 est démenti par la mesure : le schéma porte exactement ce que la chambre HIIT demande", litige: "aucune donnée n'y est jamais arrivée — voir b-sy-jamais-ecrit", preuve: { sonde: "GET /rest/v1/cardio_phases?select=seconds,speed,cycle_index,kind,incline,position&limit=1 + témoin colonne_temoin_bidon — 05-09 Paris, clé publiable", reponse: "200 [] · le témoin → 400 {\"code\":\"42703\",\"message\":\"column cardio_phases.colonne_temoin_bidon does not exist\"} ; count(*) = 0" } },
  { id: "b-tb-cards", genre: "table", nom: "cards", titre: "cards", page: "serveur", domaine: "forge", etat: "ok", quoi: "Le catalogue des cartes du set, écrit par la forge", preuve: { fichier: "supabase/migrations/20260814180000_cartes_lune.sql" } },
  { id: "b-tb-user-cards", genre: "table", nom: "user_cards", titre: "user_cards", page: "serveur", domaine: "forge", etat: "srv", reference: true, quoi: "Ta collection. Elle se remplit à chaque tirage — et aucune ligne de l'app ne la lit. Le mur du profil compte en mémoire et repart à zéro", preuve: { fichier: "supabase/migrations/20260814180000_cartes_lune.sql" } },
  { id: "b-tb-syntheses", genre: "table", nom: "syntheses", titre: "`syntheses` : monter `ProgressionView`, ou supprimer", page: "serveur", domaine: "stories", etat: "srv", cout: "1 h", quoi: "Le bilan hebdomadaire (edge function)", preuve: { fichier: "Woop/Views/ProgressionView.swift", lignes: "14" } },
  { id: "b-tb-booster-progress", genre: "table", nom: "booster_progress", titre: "`booster_progress` : table morte — supprimer ou réalimenter", page: "serveur", domaine: "eco", etat: "abs", cout: "1 h", quoi: "Morte. Elle portait la jauge ; personne ne l'écrivait, donc la jauge affichait 0/100 en permanence. Remplacée par un calcul", preuve: { fichier: "supabase/migrations/20260828160000_wallet_coffre.sql", lignes: "50" } },
  { id: "b-fn-cloturer-seance", genre: "fonction", nom: "cloturer_seance", titre: "cloturer_seance", page: "serveur", domaine: "eco", etat: "ok", quoi: "Fin de séance : crédite les pièces (converties par 100 dans la même transaction), donne un sachet forfaitaire, tire la pièce d'argent ; REJOUÉE, elle rend le STOCKÉ (`rejeu`, mêmes pièces et sachet, `argent_seance`) — de quoi composer la pile de la page noire depuis une réponse (30-08 soir)", note: "oui — SacreServeur.swift:213 ; le sachet est accordé À LA CLÔTURE (t0, via l'outbox) ; `argent` garde son sens « tombée à cet appel », l'app l'incrémente ; `solde_argent`, `sachets_convertis`, `rejeu` ne sont pas encore décodés (J2)", preuve: { sonde: "POST /rest/v1/rpc/cloturer_seance ×2, uuid neuf, 4 séries — 30-08 18:49 Paris, tools/annonces/verif_backend_coffre.py (TOUT EST VERT, 47 preuves), compte de test", reponse: "#1 {pieces 80, booster_neuf true, sachets_convertis 1, solde 16, rejeu false} · #2 {rejeu true, pieces 80, même booster_id, booster_neuf false, argent false, argent_seance stocké, sachets_convertis 0} ; le coffre n'a pas bougé" } },
  { id: "b-fn-etat-coffre", genre: "fonction", nom: "etat_coffre", titre: "etat_coffre", page: "serveur", domaine: "eco", etat: "ok", quoi: "Le coffre en un appel : or, argent, sachets, jauge, prix, taux, `noirs_ouverts` — et depuis le 30-08 soir `jour`, `retour_disponible`, `retour_prochain` (le prochain minuit Paris), `flamme` {jours, aujourdhui_fait} et `pieces_retour_quotidien` (20260830220000) ; `reste` = solde (< 100 par construction)", note: "oui — SacreServeur.swift EtatCoffre décode les six clés nouvelles en OPTIONNELS (clé absente = inchangée), EconomieWoop.appliquer les pose ; VU au sim : la page Or dit « 23 » et « +10 coins in 4 hours » = solde_or 23 et retour_prochain 22:00 UTC du serveur", preuve: { sonde: "POST /rest/v1/rpc/etat_coffre après 20260830220000, puis sim kat-booster, compte de test (-skipAuth -sessionBanc -outboxBanc), 30-08 ~21:45 Paris, build dd-j2", reponse: "{\"pieces_retour_quotidien\":10,\"jour\":\"2026-08-30\",\"retour_disponible\":false,\"retour_prochain\":\"2026-08-30T22:00:00+00:00\",\"flamme\":{\"jours\":0,\"aujourdhui_fait\":false},\"solde_or\":23,\"boosters_or\":65} — l'écran : 23 · « +10 coins in 4 hours »" } },
  { id: "b-fn-historique-gains", genre: "fonction", nom: "historique_gains", titre: "historique_gains", page: "serveur", domaine: "eco", etat: "ok", quoi: "Le journal, pièces et boosters mélangés, du plus récent au plus ancien", note: "oui", preuve: { fichier: "Woop/Services/SacreServeur.swift", lignes: "383" } },
  { id: "b-fn-claim-booster", genre: "fonction", nom: "claim_booster", titre: "`claim_booster` : fermée au serveur, plus aucun appelant", page: "serveur", domaine: "eco", etat: "abs", quoi: "L'achat d'un sachet contre 100 pièces — sans objet depuis la conversion (le solde ne dépasse plus 99) : révoquée le 30-08 soir (Q9), et l'app ne l'appelle plus (J2 : `acheterBooster` retiré, les deux branches CoffreV2 / ProfilLune ne font plus qu'un haptique)", preuve: { git: "grep -rn acheterBooster|claimBooster Woop → SacreServeur.claimBooster seule, sans appelant (30-08 soir) ; rpc/claim_booster → 403/42501" } },
  { id: "b-fn-ouvrir-booster", genre: "fonction", nom: "ouvrir_booster", titre: "ouvrir_booster", page: "serveur", domaine: "eco", etat: "ok", quoi: "Consomme un sachet orange à l'ENGAGEMENT, avant la forge ; un sachet ouvert non scellé (< 6 h) est REPRIS au lieu d'en ouvrir un second (30-08)", note: "oui — EconomieWoop.swift:291 consommerBooster ← BoosterLab.swift:2317 (9ef6da1)", preuve: { sonde: "POST /rest/v1/rpc/ouvrir_booster {\"p_legendaire\":false} ×2 — 30-08 14:35, tools/sacre/verif_backend_sachet.py (22 ✓), compte de test ; témoin rpc/fonction_inventee_temoin → 404", reponse: "200 {\"ouvert\":true,\"reprise\":true,\"booster_id\":\"34e6bfdd-…\"} · rejoué → le MÊME id, boosters_or 47→47 · après scellement → 6b396e46-…, boosters_or 46" } },
  { id: "b-fn-claim-retour-quotidien", genre: "fonction", nom: "claim_retour_quotidien", titre: "claim_retour_quotidien", page: "serveur", domaine: "eco", etat: "ok", quoi: "+10 pièces une fois par jour — le jour de la MAISON (`fuseau_jour` = Europe/Paris depuis le 30-08 soir), écrit dans le carnet ; rejouée, `credite:false` sans erreur", note: "oui — depuis le 30-08 soir l'app ne l'appelle PLUS toute seule au premier plan : `EconomieWoop.reclamerRetour()` la poste dans l'outbox AU TAP du bouton Claim de la card Welcome Back (WoopApp.swift, hôte à la racine) ; le tap lui-même n'a pas encore été mesuré à l'écran (le jour du compte de test était pris)", preuve: { sonde: "POST /rest/v1/rpc/claim_retour_quotidien ×2 — 30-08 18:49 Paris, tools/annonces/verif_backend_coffre.py, compte de test", reponse: "#1 {credite true, jour 2026-08-30, montant 10} exactement quand retour_disponible le promettait · #2 {credite false} · le carnet : jour = 2026-08-30 (Paris)" } },
  { id: "b-fn-reclamer-noeud-chemin", genre: "fonction", nom: "reclamer_noeud_chemin", titre: "reclamer_noeud_chemin", page: "serveur", domaine: "chemin", etat: "ok", quoi: "Délègue à `tirer_noeud_chemin` et IGNORE montant, monnaie et robes envoyés par l'appelant (avant le 30-08 : un million d'argent au choix du client)", note: "oui — seul appelant restant : l'outbox héritée OutboxGains.swift:212-214 ; RewardChemin.poster est mort", preuve: { sonde: "POST /rest/v1/rpc/reclamer_noeud_chemin (3, 1000000, 'silver', {}) — 30-08 14:35, tools/sacre/verif_backend_sachet.py (22 ✓), compte de test", reponse: "200 {\"deja_reclame\":true}, solde_argent 0→0" } },
  { id: "b-fn-tirer-noeud-chemin", genre: "fonction", nom: "tirer_noeud_chemin", titre: "tirer_noeud_chemin", page: "serveur", domaine: "chemin", etat: "ok", quoi: "Le tirage d'un nœud ET la pitié vivent au serveur (30-08) ; nœud borné et rapproché de sa piste ; rejouée, même résultat. Depuis le 30-08 soir, une enveloppe du même nom ajoute `sachets_convertis` (le tirage vit dans `tirer_noeud_chemin_brut`, privée)", note: "oui — RewardChemin.swift:224 tirerAuServeur via SacreServeur.swift:143", preuve: { sonde: "POST /rest/v1/rpc/tirer_noeud_chemin (21,true) puis (3,true) — 30-08 18:49 Paris, tools/annonces/verif_backend_coffre.py (TOUT EST VERT, 47 preuves), compte de test", reponse: "(21) → {montant 197, deja_reclame false, sachets_convertis 2, solde 23} · (3, déjà tiré) → {deja_reclame true, sachets_convertis 0}" } },
  { id: "b-fn-noeuds-reclames", genre: "fonction", nom: "noeuds_chemin_reclames", titre: "`noeuds_chemin_reclames()` : tour complet jamais vu", page: "serveur", domaine: "chemin", etat: "srv", cout: "1 h", quoi: "Rend les nœuds du chemin déjà payés — la lecture qui manquait (29-08)", note: "écrite côté app, sonde 200 [] — tour complet non mesuré", preuve: { fichier: "Woop/Services/SacreServeur.swift", lignes: "421" } },
  { id: "b-fn-poser-faits", genre: "fonction", nom: "poser_faits_seance", titre: "`poser_faits_seance()` déployée — personne ne l'appelle", page: "serveur", domaine: "stories", etat: "srv", cout: "1 j", quoi: "Le moteur de faits (30-08) : range ce qu'une séance a été — `top_muscu`, `top_cardio`, `double_jour` — avec en quoi elle s'est dépassée. Idempotente, et un `kind` inconnu est ignoré, jamais refusé", note: "personne ne l'appelle encore", preuve: { fichier: "supabase/migrations/20260830100000_moteur_faits.sql" } },
  { id: "b-fn-roll-rare", genre: "fonction", nom: "roll_rare", titre: "roll_rare", page: "serveur", domaine: "eco", etat: "ok", quoi: "Le tirage de la pièce d'argent, 1 chance sur 30. Privée — appelée par la clôture seulement", note: "interne", preuve: { fichier: "supabase/migrations/20260829130000_roll_rare_prive.sql" } },
  { id: "b-fn-convertir-pieces", genre: "fonction", nom: "convertir_pieces", titre: "convertir_pieces", page: "serveur", domaine: "eco", etat: "ok", quoi: "La conversion (30-08 soir) : tant que le solde jaune ≥ prix, un sachet `conversion` + une ligne -100, sous verrou par utilisatrice ; le témoin d'idempotence est le solde lui-même. Privée — appelée par le déclencheur `coin_ledger_convertir` et, une fois, par la migration (le stock d'avant)", note: "interne", preuve: { sonde: "cloturer_seance : solde 36 + 80 → sachets_convertis 1, solde 16 ; rpc/convertir_pieces direct — 30-08 18:49 Paris, tools/annonces/verif_backend_coffre.py (TOUT EST VERT, 47 preuves), compte de test", reponse: "403 {\"code\":\"42501\"} en direct ; la ligne -100 lue dans le carnet" } },
  { id: "b-fn-convertis-transaction", genre: "fonction", nom: "convertis_transaction", titre: "convertis_transaction", page: "serveur", domaine: "eco", etat: "ok", quoi: "Ce que CETTE transaction a converti — porté par `set_config`, relu par cloturer_seance, claim_retour_quotidien et tirer_noeud_chemin pour rendre `sachets_convertis`", note: "interne", preuve: { sonde: "les trois réponses — 30-08 18:49 Paris, tools/annonces/verif_backend_coffre.py (TOUT EST VERT, 47 preuves), compte de test", reponse: "sachets_convertis 1 (clôture) · 0 (retour) · 2 (nœud 21) ; en direct → 403/42501" } },
  { id: "b-fn-jour-courant", genre: "fonction", nom: "jour_courant", titre: "jour_courant", page: "serveur", domaine: "eco", etat: "ok", quoi: "Le jour de la maison : `(now() at time zone fuseau_jour())::date` — la seule définition du « jour » (Welcome Back, flamme, retour_disponible)", note: "interne — l'app lit etat_coffre().jour", preuve: { sonde: "etat_coffre().jour et rpc/jour_courant direct — 30-08 18:49 Paris, tools/annonces/verif_backend_coffre.py (TOUT EST VERT, 47 preuves), compte de test", reponse: "jour = 2026-08-30 = aujourd'hui à Paris ; en direct → 403/42501" } },
  { id: "b-fn-fuseau-jour", genre: "fonction", nom: "fuseau_jour", titre: "fuseau_jour", page: "serveur", domaine: "eco", etat: "ok", quoi: "Lit la règle `fuseau_jour` et retombe sur UTC si le nom est inconnu de la base des fuseaux (une ligne mal tapée ne rend pas le coffre muet)", note: "⚠️ MESURÉ le 13-09 sur 23 séances / 88 séries : widget_volume('semaine') → 57014 statement timeout via PostgREST (12,7 s au chronomètre depuis postgres ; le bloc du record de semaine seul : 8 324 ms). La validation `exists (select 1 from pg_timezone_names …)` ÉNUMÈRE LES FICHIERS de fuseaux à chaque lecture (~95 ms), et trois fonctions l'appellent DANS leurs requêtes (widget_volume, widget_hiit, widget_peak) — stable, pas immutable, donc évaluée par ligne : 88 × 95 ms. Corrigé par 20260913120000_fuseau_jour_rapide.sql : validation par TENTATIVE (perform now() at time zone v, 22023 si le nom est inconnu), même signature, même valeur, même repli UTC, aucun appelant ne bouge ; déployée par supabase db push --linked le 13-09 ~12:05. Après : widget_volume 15-26 ms, hiit 17 ms, regularite 18-22 ms, peak 17-38 ms, fuseau_jour() seule 2,5 ms. Historique : interne", preuve: { sonde: "select public.widget_volume('semaine') avec request.jwt.claims du compte de test et clock_timestamp() - now() — avant puis après la migration, 13-09 ~12:05 Paris", reponse: "avant : 57014 canceling statement due to statement timeout via PostgREST, 00:00:12.72 via postgres · après : 00:00:00.0257 · fuseau_jour() seule : 00:00:00.0025 → Europe/Paris" } },
  { id: "b-fn-flamme", genre: "fonction", nom: "flamme", titre: "`flamme()` : posée au serveur, personne ne l'affiche", page: "serveur", domaine: "eco", etat: "srv", cout: "1 j", quoi: "La flamme (30-08 soir) : dérivée des séances (`workouts.ended_at` dans le fuseau de la maison) → {jours, aujourdhui_fait} ; hier compte si aujourd'hui n'est pas fait ; jamais stockée, ne rapporte rien", note: "aussi dans etat_coffre().flamme ; AFFICHÉE au profil depuis le J2 (ProfilLune pastilleFlamme : flame mat à 0, laque blanche au-delà, un point si aujourd'hui est fait) — vue à 0 au sim, l'état allumé pas encore mesuré", preuve: { sonde: "fixture de 3 séances (J-3 · J-1 · J0 à 00:30 Paris = la veille en UTC) semée puis retirée — 30-08 18:49 Paris, tools/annonces/verif_backend_coffre.py (TOUT EST VERT, 47 preuves), compte de test", reponse: "{\"jours\":2,\"aujourdhui_fait\":true} — en UTC J0 serait hier ; le recalcul local rend 2 / true" } },
  { id: "b-fn-tirer-noeud-chemin-brut", genre: "fonction", nom: "tirer_noeud_chemin_brut", titre: "tirer_noeud_chemin_brut", page: "serveur", domaine: "chemin", etat: "ok", quoi: "L'ancienne `tirer_noeud_chemin` du 30-08 midi, renommée le soir : le tirage et la pitié, derrière l'enveloppe qui ajoute `sachets_convertis`", note: "interne", preuve: { sonde: "rpc/tirer_noeud_chemin_brut direct — 30-08 18:49 Paris, tools/annonces/verif_backend_coffre.py (TOUT EST VERT, 47 preuves), compte de test", reponse: "403/42501 ; via l'enveloppe → 200" } },
  { id: "b-fn-solde-or", genre: "fonction", nom: "solde_or", titre: "solde_or", page: "serveur", domaine: "eco", etat: "ok", quoi: "L'addition du carnet en jaune", note: "interne", preuve: { fichier: "supabase/migrations/20260828190000_gains_coffre.sql", lignes: "25" } },
  { id: "b-fn-regles-annonces", genre: "fonction", nom: "regles_annonces", titre: "Appeler `regles_annonces()` — personne ne l'appelle", page: "serveur", domaine: "annonces", etat: "srv", cout: "1 j", quoi: "Les 21 clés de rythme (annonces.sql:96-152), moins les 3 rare_* : 18 en un appel", note: "non", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "174" } },
  { id: "b-fn-solde-argent", genre: "fonction", nom: "solde_argent", titre: "`solde_argent` : « sans appelant » ici, appelée en :104", page: "serveur", domaine: "eco", etat: "srv", cout: "1 h", quoi: "L'addition du carnet en argent", note: "non", litige: "« sans appelant » sur la carte, mais appelée en SacreServeur.swift:104", preuve: { fichier: "Woop/Services/SacreServeur.swift", lignes: "104" } },
  { id: "b-fn-claim-legendaire", genre: "fonction", nom: "claim_booster_legendaire", titre: "claim_booster_legendaire", page: "serveur", domaine: "eco", etat: "ok", quoi: "C'est ELLE la consommation du noir : la pièce d'argent part, le sachet noir s'ouvre ; rejouée, elle rend le même sachet sans reprendre de pièce — 200 sur un refus métier, plus jamais 500 (30-08)", note: "oui — EconomieWoop.swift:291 (legendaire: true) via SacreServeur.swift:128 claimLegendaire ; ouvrir_booster(true) n'est plus appelée pour le noir", preuve: { sonde: "POST /rest/v1/rpc/claim_booster_legendaire ×2 — 30-08 14:35, tools/sacre/verif_backend_sachet.py (22 ✓), compte de test", reponse: "#1 → 200 {\"ouvert\":true,\"reprise\":false,\"booster_id\":\"fe87cd5c-…\",\"solde_argent\":0,\"prix\":1} · #2 → 200 même id, \"reprise\":true, \"prix\":0 · etat_coffre().noirs_ouverts 0→1" } },
  { id: "b-fn-solde-noir", genre: "fonction", nom: "solde_noir", titre: "`solde_noir()` et `solde_or()` : jamais appelées du client", page: "serveur", domaine: "eco", etat: "abs", cout: "1 h", quoi: "Ancien nom d'`solde_argent`, gardé par prudence", note: "à retirer — solde_or reste interne (gains_coffre.sql:25)", preuve: { fichier: "supabase/migrations/20260828120000_booster_noir.sql", lignes: "191" } },
  { id: "b-rg-pieces-par-serie", genre: "regle", nom: "pieces_par_serie", titre: "pieces_par_serie", page: "serveur", domaine: "eco", etat: "ok", valeur: "20", quoi: "Ce qu'une série rapporte", preuve: { fichier: "supabase/migrations/20260828160000_wallet_coffre.sql" } },
  { id: "b-rg-prix-booster", genre: "regle", nom: "prix_booster", titre: "prix_booster", page: "serveur", domaine: "eco", etat: "ok", valeur: "100", quoi: "Ce qu'un sachet coûte", preuve: { fichier: "supabase/migrations/20260828160000_wallet_coffre.sql" } },
  { id: "b-rg-prix-booster-legendaire", genre: "regle", nom: "prix_booster_legendaire", titre: "prix_booster_legendaire", page: "serveur", domaine: "eco", etat: "ok", valeur: "1", quoi: "Pièces d'argent pour un sachet noir", preuve: { fichier: "supabase/migrations/20260828120000_booster_noir.sql" } },
  { id: "b-rg-pieces-retour-quotidien", genre: "regle", nom: "pieces_retour_quotidien", titre: "pieces_retour_quotidien", page: "serveur", domaine: "eco", etat: "ok", valeur: "10", quoi: "Le versement de connexion", preuve: { fichier: "supabase/migrations/20260828190000_gains_coffre.sql" } },
  { id: "b-rg-fuseau-jour", genre: "regle", nom: "fuseau_jour", titre: "fuseau_jour", page: "serveur", domaine: "eco", etat: "ok", valeur: "Europe/Paris", quoi: "Le fuseau du « jour » de la maison (30-08 soir) — une ligne à changer si elle déménage ; jamais le fuseau du téléphone (le farm par voyage dans le temps)", preuve: { sonde: "claim_retour_quotidien.jour, le carnet, etat_coffre().retour_prochain — 30-08 18:49 Paris, tools/annonces/verif_backend_coffre.py (TOUT EST VERT, 47 preuves), compte de test", reponse: "jour = 2026-08-30 (Paris) ; retour_prochain = 22:00 UTC = minuit Paris" } },
  { id: "b-rg-chemin-taux-piece-noire", genre: "regle", nom: "chemin_taux_piece_noire", titre: "chemin_taux_piece_noire", page: "serveur", domaine: "chemin", etat: "ok", valeur: "0.06", quoi: "Taux du tirage : une pièce noire au nœud — lue par tirer_noeud_chemin (30-08)", preuve: { sonde: "GET /rest/v1/reward_rules?key=like.chemin_* — 30-08 14:36, woochoper-ios-cd", reponse: "0.06 lu en base" } },
  { id: "b-rg-chemin-taux-double-legendaire", genre: "regle", nom: "chemin_taux_double_legendaire", titre: "chemin_taux_double_legendaire", page: "serveur", domaine: "chemin", etat: "ok", valeur: "0.01", quoi: "Taux du tirage : deux sachets noirs d'un coup — lue par tirer_noeud_chemin (30-08)", preuve: { sonde: "GET /rest/v1/reward_rules?key=like.chemin_* — 30-08 14:36, woochoper-ios-cd", reponse: "0.01 lu en base" } },
  { id: "b-rg-chemin-taux-rare", genre: "regle", nom: "chemin_taux_rare", titre: "chemin_taux_rare", page: "serveur", domaine: "chemin", etat: "ok", valeur: "0.11", quoi: "Taux du tirage : un lot rare — lue par tirer_noeud_chemin (30-08)", preuve: { sonde: "GET /rest/v1/reward_rules?key=like.chemin_* — 30-08 14:36, woochoper-ios-cd", reponse: "0.11 lu en base" } },
  { id: "b-rg-chemin-pitie", genre: "regle", nom: "chemin_pitie", titre: "chemin_pitie", page: "serveur", domaine: "chemin", etat: "ok", valeur: "12", quoi: "La pitié : tirages sans rareté avant le lot forcé — dérivée du journal, jamais un compteur — lue par tirer_noeud_chemin (30-08)", preuve: { sonde: "GET /rest/v1/reward_rules?key=like.chemin_* — 30-08 14:36, woochoper-ios-cd", reponse: "12 lu en base" } },
  { id: "b-rg-chemin-pieces-min", genre: "regle", nom: "chemin_pieces_min", titre: "chemin_pieces_min", page: "serveur", domaine: "chemin", etat: "ok", valeur: "100", quoi: "Plancher d'un nœud en pièces (176 tiré au banc) — lue par tirer_noeud_chemin (30-08)", preuve: { sonde: "GET /rest/v1/reward_rules?key=like.chemin_* — 30-08 14:36, woochoper-ios-cd", reponse: "100 lu en base" } },
  { id: "b-rg-chemin-pieces-max", genre: "regle", nom: "chemin_pieces_max", titre: "chemin_pieces_max", page: "serveur", domaine: "chemin", etat: "ok", valeur: "200", quoi: "Plafond d'un nœud en pièces — lue par tirer_noeud_chemin (30-08)", preuve: { sonde: "GET /rest/v1/reward_rules?key=like.chemin_* — 30-08 14:36, woochoper-ios-cd", reponse: "200 lu en base" } },
  { id: "b-rg-chemin-chapitres", genre: "regle", nom: "chemin_chapitres", titre: "chemin_chapitres", page: "serveur", domaine: "chemin", etat: "srv", reference: true, valeur: "5", quoi: "Nombre de chapitres (29-08) — relue par l'app pour COMPARER à EcranSpec, jamais appliquée ; rang 3 / rang 8 lus par tirer_noeud_chemin", preuve: { fichier: "supabase/migrations/20260829170000_regles_chemin.sql", lignes: "39-50" } },
  { id: "b-rg-chemin-noeuds-par-chapitre", genre: "regle", nom: "chemin_noeuds_par_chapitre", titre: "chemin_noeuds_par_chapitre", page: "serveur", domaine: "chemin", etat: "srv", reference: true, valeur: "9", quoi: "Nœuds par chapitre (29-08) — relue par l'app pour COMPARER à EcranSpec, jamais appliquée ; rang 3 / rang 8 lus par tirer_noeud_chemin", preuve: { fichier: "supabase/migrations/20260829170000_regles_chemin.sql", lignes: "39-50" } },
  { id: "b-rg-chemin-seances-par-chapitre", genre: "regle", nom: "chemin_seances_par_chapitre", titre: "chemin_seances_par_chapitre", page: "serveur", domaine: "chemin", etat: "srv", reference: true, valeur: "7", quoi: "Séances par chapitre (29-08) — relue par l'app pour COMPARER à EcranSpec, jamais appliquée ; rang 3 / rang 8 lus par tirer_noeud_chemin", preuve: { fichier: "supabase/migrations/20260829170000_regles_chemin.sql", lignes: "39-50" } },
  { id: "b-rg-chemin-rang-recompense-milieu", genre: "regle", nom: "chemin_rang_recompense_milieu", titre: "chemin_rang_recompense_milieu", page: "serveur", domaine: "chemin", etat: "srv", reference: true, valeur: "3", quoi: "Rang de la récompense du milieu (29-08) — relue par l'app pour COMPARER à EcranSpec, jamais appliquée ; rang 3 / rang 8 lus par tirer_noeud_chemin", preuve: { fichier: "supabase/migrations/20260829170000_regles_chemin.sql", lignes: "39-50" } },
  { id: "b-rg-chemin-rang-tresor", genre: "regle", nom: "chemin_rang_tresor", titre: "chemin_rang_tresor", page: "serveur", domaine: "chemin", etat: "srv", reference: true, valeur: "8", quoi: "Rang du trésor (29-08) — relue par l'app pour COMPARER à EcranSpec, jamais appliquée ; rang 3 / rang 8 lus par tirer_noeud_chemin", preuve: { fichier: "supabase/migrations/20260829170000_regles_chemin.sql", lignes: "39-50" } },
  { id: "b-rg-popups-max-seance", genre: "regle", nom: "popups_max_seance", titre: "popups_max_seance", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "4", quoi: "Budget d'attention par séance", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "98-151" } },
  { id: "b-rg-reward-monetaire-max-seance", genre: "regle", nom: "reward_monetaire_max_seance", titre: "reward_monetaire_max_seance", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "1", quoi: "Une seule récompense en pièces", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "98-151" } },
  { id: "b-rg-video-max-seance", genre: "regle", nom: "video_max_seance", titre: "video_max_seance", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "1", quoi: "Une seule vidéo", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "98-151" } },
  { id: "b-rg-notifs-max-seance", genre: "regle", nom: "notifs_max_seance", titre: "notifs_max_seance", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "6", quoi: "Plafond des dalles", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "98-151" } },
  { id: "b-rg-notif-budget", genre: "regle", nom: "notif_consomme_budget", titre: "notif_consomme_budget", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "false", quoi: "Une dalle ne mange pas un pop-up — TRANCHÉ le 30-08 (et ecart_exige_les_deux = true : 3 séries ET 6 min) ; la valeur du fichier est la bonne, personne ne la lit encore", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "102-110, 146-151" } },
  { id: "b-rg-ecart-min-series", genre: "regle", nom: "ecart_min_series", titre: "ecart_min_series", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "3", quoi: "Écart mini entre deux annonces", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "98-151" } },
  { id: "b-rg-ecart-min-minutes", genre: "regle", nom: "ecart_min_minutes", titre: "ecart_min_minutes", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "6", quoi: "… et en minutes", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "98-151" } },
  { id: "b-rg-ecart-exige-les-deux", genre: "regle", nom: "ecart_exige_les_deux", titre: "ecart_exige_les_deux", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "true", quoi: "Les deux, ou l'un des deux", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "98-151" } },
  { id: "b-rg-bonus-fort-progres-surprise", genre: "regle", nom: "bonus_fort / progres / surprise", titre: "bonus_fort / progres / surprise", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "40 / 30 / 20", quoi: "Les trois bonus", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "98-151" } },
  { id: "b-rg-bonus-plafond-seance", genre: "regle", nom: "bonus_plafond_seance", titre: "bonus_plafond_seance", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "60", quoi: "Plafond des bonus", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "98-151" } },
  { id: "b-rg-meme-fait-max-seance-semaine", genre: "regle", nom: "meme_fait_max_seance / semaine", titre: "meme_fait_max_seance / semaine", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "1 / 2", quoi: "Anti-ressassage", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "98-151" } },
  { id: "b-rg-welcome", genre: "regle", nom: "welcome_absence_jours", titre: "Clés `welcome_*` déployées — aucun Swift ne les lit", page: "serveur", domaine: "annonces", etat: "srv", cout: "1 j", valeur: "0", quoi: "Absence requise — 0 depuis le 30-08 : à chaque connexion", note: "0 / 0 / 31 vérifiés en base (ANALYSE-WELCOME-BACK.md:43-47), lus par personne", preuve: { fichier: "supabase/migrations/20260830090000_welcome_chaque_connexion.sql", lignes: "37-44" } },
  { id: "b-rg-welcome-cooldown-jours", genre: "regle", nom: "welcome_cooldown_jours", titre: "welcome_cooldown_jours", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "0", quoi: "Pause entre deux — plus aucune", preuve: { fichier: "supabase/migrations/20260830090000_welcome_chaque_connexion.sql", lignes: "37-44" } },
  { id: "b-rg-welcome-max-mois", genre: "regle", nom: "welcome_max_mois", titre: "welcome_max_mois", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "31", quoi: "Maximum par mois — 31 = au plus un par jour, dans l'unité de la clé (pas une désactivation)", preuve: { fichier: "supabase/migrations/20260830090000_welcome_chaque_connexion.sql", lignes: "37-44" } },
  { id: "b-rg-annonce-une-par-evenement", genre: "regle", nom: "annonce_une_par_evenement", titre: "annonce_une_par_evenement", page: "serveur", domaine: "annonces", etat: "srv", reference: true, valeur: "true", quoi: "Un gain ne se dit qu'une fois", preuve: { fichier: "supabase/migrations/20260829120000_annonces.sql", lignes: "98-151" } },
  { id: "b-rg-top", genre: "regle", nom: "top_mesures_muscu", titre: "Les 4 clés `top_*` posées en base, lues par personne", page: "serveur", domaine: "stories", etat: "srv", cout: "1 j", valeur: "séries · poids levé", quoi: "Se dépasser en muscu — il suffit d'en battre UNE", preuve: { fichier: "supabase/migrations/20260830100000_moteur_faits.sql" } },
  { id: "b-rg-top-mesures-cardio", genre: "regle", nom: "top_mesures_cardio", titre: "top_mesures_cardio", page: "serveur", domaine: "stories", etat: "srv", reference: true, valeur: "HIIT · vitesse×durée", quoi: "Se dépasser en cardio — il suffit d'en battre UNE", preuve: { fichier: "supabase/migrations/20260830100000_moteur_faits.sql" } },
  { id: "b-rg-top-fenetre-jours", genre: "regle", nom: "top_fenetre_jours", titre: "top_fenetre_jours", page: "serveur", domaine: "stories", etat: "srv", reference: true, valeur: "7", quoi: "La « semaine », glissante", preuve: { fichier: "supabase/migrations/20260830100000_moteur_faits.sql" } },
  { id: "b-rg-top-min-seances", genre: "regle", nom: "top_min_seances", titre: "top_min_seances", page: "serveur", domaine: "stories", etat: "srv", reference: true, valeur: "2", quoi: "Sans lui, la première séance de la semaine est mécaniquement la meilleure — se dépasser suppose un précédent", preuve: { fichier: "supabase/migrations/20260830100000_moteur_faits.sql" } },
  { id: "b-rg-rare", genre: "regle", nom: "rare_* (3 clés)", titre: "`rare_*` « jamais exposées » — `reward_rules` lue en REST", page: "serveur", domaine: "eco", etat: "ok", cout: "1 j", valeur: "cachées", quoi: "La rareté de la pièce d'argent — jamais exposées au client, sinon elle devient farmable", note: "interne", litige: "« jamais exposées », mais l'app lit reward_rules en REST (SacreServeur.swift:434) sans policy de colonne (annonces.sql:179)", preuve: { fichier: "Woop/Services/SacreServeur.swift", lignes: "434" } },
  { id: "b-ed-forge-card", genre: "edge", nom: "forge-card", titre: "forge-card", page: "serveur", domaine: "forge", etat: "ok", quoi: "Tire une carte (pool commun ~1 s, ou neuve à l'IA 60-90 s), la rareté décidée ici ; depuis le 30-08 elle SCELLE la carte sur le sachet AVANT la collection (update … is('card_id', null) = la réservation : deux forges concurrentes = une carte)", note: "oui — redéployée 30-08 ; le client envoie booster_id (BoosterLab.swift:2302-2330 : consommer PUIS forger), mesuré au sim 14:38 sous -boosterScelle : user_boosters 86540dfa… → card_id f9358e28… (Vallée noire, common), user_cards obtained_at 12:39:35Z", preuve: { sonde: "POST /functions/v1/forge-card {\"booster_id\":\"34e6bfdd-…\"} ×2 — 30-08 14:35, tools/sacre/verif_backend_sachet.py (22 ✓), compte de test", reponse: "#1 → 200 carte bba6dc85-… (rare) · #2 → 200 la MÊME carte" } },
  { id: "b-edge-weekly", genre: "edge", nom: "weekly-synthesis", titre: "`weekly-synthesis` : écrite, jamais déployée, jamais montée", page: "serveur", domaine: "stories", etat: "abs", cout: "1 j", quoi: "Le bilan hebdomadaire (Claude) — le code existe dans le dépôt, la fonction n'est pas au serveur, et ProgressionView qui l'appelle n'est montée nulle part", preuve: { sonde: "supabase functions list (jeton .secrets, 30-08) puis POST /functions/v1/weekly-synthesis {}", reponse: "functions list → forge-card SEULE (ACTIVE v4) · POST → 404 {\"code\":\"NOT_FOUND\"}" } },

  // ─────────────────────────────────────────────────────────────────────────
  // LES DONNÉES DES WIDGETS (05-09) — ce que les quatre cards de la home et
  // leurs « chambres longues » demandent. TOUT est calculé DANS LE TÉLÉPHONE
  // aujourd'hui : `SemaineStats.calcule()` lit les `Workout` en mémoire et
  // n'appelle aucune fonction serveur. Rien de ce qui suit n'est mesuré au
  // serveur — les états sont lus dans le code, fichier:ligne.
  // ─────────────────────────────────────────────────────────────────────────
  { id: "b-wd-semainestats", genre: "fonction", nom: "SemaineStats.calcule", titre: "Les quatre widgets sont calculés DANS le téléphone", page: "widgets", domaine: "widgets", etat: "loc", cout: "chantier", quoi: "Une seule fonction Swift produit les quatre widgets de la home — régularité, volume, HIIT peak, peak effort — en repassant sur les séances en mémoire. Aucun appel serveur, donc : rien n'est comparable entre appareils, rien ne survit à une réinstallation, et la home ne peut pas se peindre avant que la synchro ait fini", note: "la lecture manque partout (SupabaseSync n'a qu'un push) — c'est la cause commune des 🟡 de cette section", preuve: { fichier: "Woop/Views/WidgetsCards.swift", lignes: "2207-2293" } },
  { id: "b-wd-hiitpeak-groupage", genre: "fonction", nom: "SemaineStats.hiitPeak", titre: "`hiitPeak()` compte des répétitions qui n'existent pas", page: "widgets", domaine: "widgets", etat: "men", cout: "1 h", quoi: "Elle déduit le « × N » d'un intervalle en groupant les phases d'effort par la clé (kindRaw | speed | seconds) IDENTIQUES. Or une séance réelle n'a jamais deux phases identiques : 2:00 à 17,0 puis 0:30 à 19,0 puis 1:30 à 17,5. Chaque groupe vaut donc n = 1, et la card affiche « 2:00 continuous » là où la séance comptait quatre efforts", note: "verdict 05-09 : « ce n'est pas un cycle parfait » — la card ment déjà, avant même que la chambre existe", litige: "la card annonce un fractionné régulier ; le modèle (CardioPhase) ne peut pas en produire un", preuve: { fichier: "Woop/Views/WidgetsCards.swift", lignes: "2318-2325" } },
  { id: "b-wd-seuil-effort", genre: "regle", nom: "seuil_effort_kmh", titre: "Le seuil qui définit un « effort » n'existe nulle part", page: "widgets", domaine: "widgets", etat: "abs", cout: "1 h", valeur: "15,0 (voulu)", quoi: "Un effort = un passage au-dessus de 15,0 km/h (tranché le 05-09). C'est ce seuil qui donne « 15 efforts cette semaine », le temps de pics cumulé et le compte du bilan. Il n'est écrit ni en base ni dans l'app : `hiitPeak()` utilise 9,5 km/h comme plancher de candidature, ce qui est un TROISIÈME chiffre encore", note: "à poser dans reward_rules, comme les clés du chemin — sinon la home, la chambre et le bilan compteront trois fois différemment", preuve: { fichier: "Woop/Views/WidgetsCards.swift", lignes: "2306" } },
  { id: "b-wd-segments-seance", genre: "table", nom: "cardio_phases (chambre HIIT)", titre: "Sans `cardio_phases`, la chambre HIIT n'a rien à lire", page: "widgets", domaine: "widgets", etat: "abs", cout: "chantier", quoi: "La chambre montre une séance segment par segment : chaque `CardioPhase` porte SA durée et SA vitesse (Models.swift:524), et c'est tout le sujet — dix segments dont aucun ne se répète. La table est marquée « à retravailler » depuis le 29-08 : tant qu'elle ne remonte pas, la chambre ne peut vivre que sur des données locales", note: "voir b-tb-cardio — même table, ici du point de vue de ce qui la CONSOMME", preuve: { fichier: "Woop/Models.swift", lignes: "524-546" } },
  { id: "b-wd-bilan-periodes", genre: "fonction", nom: "bilan_periode", titre: "Le bilan (semaine et mois) n'est calculé par personne", page: "widgets", domaine: "widgets", etat: "abs", cout: "1 j", quoi: "« En progrès / En recul » compare une fenêtre à la précédente : pic, temps de pics, efforts, récups, plus long trou. Demandé le 05-09 pour les QUATRE widgets, semaine ET mois. Rien ne le calcule aujourd'hui — ni l'app (SemaineStats ne compare que le volume) ni le serveur", note: "la comparaison de volume existe déjà côté app et borne les deux moitiés de semaine au même instant (le correctif du 25-08) : c'est le modèle à reprendre", preuve: { fichier: "Woop/Views/WidgetsCards.swift", lignes: "2218-2253" } },
  { id: "b-wd-phrase-ia", genre: "edge", nom: "commentaire IA du bilan", titre: "La phrase du bilan est le seul appel réseau des chambres", page: "widgets", domaine: "widgets", etat: "abs", cout: "1 j", quoi: "Une phrase écrite par l'IA sous le bilan (« tes départs sont plus rapides, mais tes récups s'allongent »). C'est la SEULE pièce des chambres qui ait besoin du réseau : elle veut un cache par période, un état de repli sans phrase, et jamais un spinner. `weekly-synthesis` fait déjà ce travail dans le dépôt — jamais déployée", note: "voir b-edge-weekly : le code existe, la fonction n'est pas au serveur", preuve: { fichier: "supabase/functions/weekly-synthesis/index.ts", lignes: "1-131" } },
  { id: "b-wd-intensite-jour", genre: "fonction", nom: "intensité d'un jour", titre: "Le halo d'intensité du calendrier n'a pas de source", page: "widgets", domaine: "widgets", etat: "abs", cout: "1 h", quoi: "Les cases du calendrier (Regularity et la vue Mois du HIIT) portent un halo à trois niveaux qui dit l'intensité de la séance du jour. `SemaineStats` calcule bien un « effort » par jour (volume + 20 kg-équivalent la minute de cardio) mais uniquement pour les rails du graphe — il n'est ni normalisé, ni exposé, ni le même d'un widget à l'autre", preuve: { fichier: "Woop/Views/WidgetsCards.swift", lignes: "2262-2281" } },
  { id: "b-wd-ascension-records", genre: "fonction", nom: "historique des records", titre: "L'ascension d'un record ne garde aucune marche", page: "widgets", domaine: "widgets", etat: "abs", cout: "1 j", quoi: "La chambre Peak montre toutes les marches d'un record (40 → 45 → 50 → 55 → 60 kg) et « Ton record de vitesse » les quatre dernières semaines. `peakEffort()` construit pourtant l'historique complet dans `maxAvant` — puis le JETTE après avoir gardé le meilleur delta", note: "la donnée est déjà là, à un `return` près : c'est le chantier le moins cher de cette liste", preuve: { fichier: "Woop/Views/WidgetsCards.swift", lignes: "2355-2361" } },
  { id: "b-wd-volume-categorie", genre: "fonction", nom: "volume par catégorie", titre: "La répartition par catégorie se recalcule à chaque ouverture", page: "widgets", domaine: "widgets", etat: "loc", cout: "1 h", quoi: "Le podium de la chambre Volume (Fessiers 38 %, Bas 31 %, Haut 21 %, Abdos 10 %) additionne `totalVolume` par `ExerciseCategory` dans le téléphone. Les `strength_sets` sont bien au serveur depuis le 29-08 : la somme pourrait y vivre", note: "le mapping catégorie → sticker est déjà tranché (bras=haut, chocolat=abdos, jambes=bas, abricot=fessiers, basket=cardio)", preuve: { fichier: "Woop/Views/ProgressPage.swift", lignes: "698-714" } },
  { id: "b-wd-cardio-sans-volume", genre: "regle", nom: "cardio dans le volume", titre: "Le cardio pèse 0 kg — dit nulle part", page: "widgets", domaine: "widgets", etat: "abs", cout: "1 h", quoi: "La chambre Volume ne compte que la fonte : une séance 100 % tapis y vaut zéro. C'est défendable, mais rien ne le DIT à l'écran, et le sticker basket (cardio) apparaîtrait à 0 kg dans la répartition. Décision à poser une fois, puis à écrire", note: "même famille que la dette du tapis HIIT (une séance 100 % tapis paie 0 pièce)", preuve: { fichier: "Woop/Views/WidgetsCards.swift", lignes: "2245-2247" } },
  // ── LA SYNCHRO, MESURÉE (05-09) ──────────────────────────────────────────
  { id: "b-sy-jamais-ecrit", genre: "table", nom: "workouts · logged_exercises · strength_sets · cardio_phases", titre: "Les quatre tables de séance sont VIDES", page: "serveur", domaine: "sync", etat: "men", cout: "chantier", quoi: "Le schéma est complet et les politiques RLS sont bonnes (CRUD « own » sur les quatre). `SupabaseSync.push()` est appelé de trois endroits (WoopApp.swift:534 et :1991, ActiveWorkoutView.swift:306). Et pourtant : count(*) = 0 partout. Les 80 lignes de `coin_ledger` appartiennent TOUTES au compte de test, écrites par les scripts de vérification des 28-30 août. Aucun compte réel n\'a jamais rien synchronisé", note: "MESURÉ le 13-09 : `push()` MARCHE dès qu'une session existe — l'app lancée au banc (-sessionBanc -demoData -syncNow, identité lue dans le jeton) a posé 23 workouts, 43 logged_exercises, 88 strength_sets et 70 cardio_phases sur le compte de test en une passe (effacés ensuite). La cause racine n'est donc pas le code de `push()` : c'est l'ABSENCE DE SESSION sur les vrais comptes (le chemin par numéro n'en ouvre pas ; celui d'Apple est le chantier d'une autre session). Et `push()` avale ses erreurs (SupabaseSync.swift:118-121) : une panne d\'auth ou de réseau est invisible. C\'est le blocage racine — aucune lecture serveur ne peut servir tant que rien n\'y monte", litige: "la carte donnait ces tables en 🟢 sur la seule preuve du code qui écrit ; la mesure dit qu\'elles sont vides", preuve: { sonde: "select count(*) sur les 4 tables + répartition de coin_ledger par compte — ' + S + '", reponse: "workouts 0 · logged_exercises 0 · strength_sets 0 · cardio_phases 0 ; coin_ledger : 80 lignes, toutes sur kat44426+woop-forge-test (28-08 → 30-08) ; 8 comptes existent" } },

  // ── LA LECTURE DES WIDGETS, DÉPLOYÉE ET MESURÉE (05-09) ──────────────────
  { id: "b-rg-seuil-effort", genre: "regle", nom: "seuil_effort_kmh", titre: "seuil_effort_kmh", page: "widgets", domaine: "widgets", etat: "srv", valeur: "15.0", quoi: "Un EFFORT est un passage au-dessus de 15,0 km/h — la seule définition, désormais en base. Elle remplace trois chiffres pour une idée : 9,5 km/h dans `hiitPeak()`, 15,0 voulu à l\'écran, 20 kg/min pour l\'équivalence cardio", note: "posée et lue par `widget_hiit()` ; aucun Swift ne la lit encore", preuve: { sonde: "select key,value from reward_rules where key=\'seuil_effort_kmh\' — ' + S + '", reponse: "[{\"key\":\"seuil_effort_kmh\",\"value\":15}]" } },
  { id: "b-fn-widget-hiit", genre: "fonction", nom: "widget_hiit", titre: "widget_hiit(fenetre)", page: "widgets", domaine: "widgets", etat: "ok", cout: "1 j", quoi: "Le HIIT d\'une fenêtre : pic, nombre d\'efforts, temps de pics, vitesse moyenne d\'effort, temps de récup, ratio — ET chaque séance avec TOUS ses segments (durée, vitesse, genre, cycle). Aucune factorisation : on compte des efforts, on ne déduit jamais un « × N »", note: "BRANCHÉE le 13-09 (Woop/Services/ChambreServeur.swift) : la chambre l'appelle à l'ouverture pour ses deux fenêtres, traduit la réponse en ChambreFenetre, et ne la DESSINE que si le téléphone n'a aucune séance sur la fenêtre (règle b-ux-chambre-serveur). déployée et mesurée bout en bout ; aucun Swift ne l\'appelle encore", preuve: { sonde: "L'app au banc (-sessionBanc -chambreVide -chambreLongue …), journal [chambre-serveur] lu en console (--console-pty), compte de test avec 23 séances de démo poussées par l'app puis effacées — 13-09 ~12:00 Paris", reponse: "widget_hiit(semaine) → 1 séance(s) · widget_hiit(mois) → 2 séance(s) ; la chambre HIIT dessine 17,0 km/h, 4 efforts, la séance à 12 segments (capture) · côté serveur 17 ms par fenêtre" } },
  { id: "b-fn-widget-regularite", genre: "fonction", nom: "widget_regularite", titre: "widget_regularite(fenetre)", page: "widgets", domaine: "widgets", etat: "ok", cout: "1 j", quoi: "Séances faites, la même chose sur la fenêtre précédente bornée AU MÊME TEMPS ÉCOULÉ, la série de semaines d\'affilée et son record (dérivés, jamais un compteur), et les jours avec leur intensité", note: "BRANCHÉE le 13-09 (Woop/Services/ChambreServeur.swift) : la chambre l'appelle à l'ouverture pour ses deux fenêtres, traduit la réponse en ChambreFenetre, et ne la DESSINE que si le téléphone n'a aucune séance sur la fenêtre (règle b-ux-chambre-serveur). déployée et mesurée ; aucun Swift ne l\'appelle encore", preuve: { sonde: "L'app au banc (-sessionBanc -chambreVide -chambreLongue …), journal [chambre-serveur] lu en console (--console-pty), compte de test avec 23 séances de démo poussées par l'app puis effacées — 13-09 ~12:00 Paris", reponse: "widget_regularite(semaine) → 8 séance(s) · (mois) → 21 ; la chambre dessine 8 / 7 séances, +2 contre la semaine passée, 4 semaines d'affilée (capture) · 18-22 ms" } },
  { id: "b-fn-widget-volume", genre: "fonction", nom: "widget_volume", titre: "widget_volume(fenetre)", page: "widgets", domaine: "widgets", etat: "ok", cout: "1 j", quoi: "Volume de la fenêtre et de la précédente, delta en %, par séance, répétitions, record de semaine sur tout l\'historique, le volume par exercice et jour par jour", note: "BRANCHÉE le 13-09 (Woop/Services/ChambreServeur.swift) : la chambre l'appelle à l'ouverture pour ses deux fenêtres, traduit la réponse en ChambreFenetre, et ne la DESSINE que si le téléphone n'a aucune séance sur la fenêtre (règle b-ux-chambre-serveur). ⚠️ Le 13-09 à 12:00 elle a d'abord RÉPONDU 500 « canceling statement due to statement timeout » à l'app : voir b-fn-fuseau-jour, corrigé et re-mesuré dans l'heure. rend `exercice_id` — le catalogue reste en Swift, l\'app fait la jointure (nom, catégorie, sticker)", preuve: { sonde: "L'app au banc (-sessionBanc -chambreVide -chambreLongue …), journal [chambre-serveur] lu en console (--console-pty), compte de test avec 23 séances de démo poussées par l'app puis effacées — 13-09 ~12:00 Paris", reponse: "avant le correctif fuseau_jour : ✗ HTTP 500 canceling statement due to statement timeout · après : widget_volume(semaine) → 8 séance(s) · (mois) → 21 ; la chambre dessine 12 703 kg, trois exercices, le podium — les MÊMES chiffres que le calcul du téléphone (capture) · 15-26 ms" } },
  { id: "b-fn-widget-peak", genre: "fonction", nom: "widget_peak", titre: "widget_peak(fenetre)", page: "widgets", domaine: "widgets", etat: "ok", cout: "1 j", quoi: "Les charges max de la fenêtre par exercice, leur précédent record, le delta, le 1RM estimé (Epley) — et L\'ASCENSION complète de celui qui a le plus progressé, ce que l\'app construisait puis jetait", note: "BRANCHÉE le 13-09 (Woop/Services/ChambreServeur.swift) : la chambre l'appelle à l'ouverture pour ses deux fenêtres, traduit la réponse en ChambreFenetre, et ne la DESSINE que si le téléphone n'a aucune séance sur la fenêtre (règle b-ux-chambre-serveur). un PREMIER n\'est pas un record battu : sans précédent le delta est null et ne compte pas — corrigé après mesure (il annonçait « +120 kg » sur un exercice jamais fait)", preuve: { sonde: "L'app au banc (-sessionBanc -chambreVide -chambreLongue …), journal [chambre-serveur] lu en console (--console-pty), compte de test avec 23 séances de démo poussées par l'app puis effacées — 13-09 ~12:00 Paris", reponse: "widget_peak(semaine) → 7 séance(s) · (mois) → 9 ; la chambre dessine 65 kg Hip thrust × 8, quatre autres pics, Records 6 battus (capture) · 17-38 ms" } },
  { id: "b-fn-fenetre-bornes", genre: "fonction", nom: "fenetre_bornes · regle_num · effort_seance", titre: "Les trois aides de la lecture des widgets", page: "widgets", domaine: "widgets", etat: "srv", reference: true, quoi: "`fenetre_bornes(fenetre)` rend les quatre bornes — et la fenêtre précédente est bornée AU MÊME TEMPS ÉCOULÉ (le correctif du 25-08 : sans ça le bilan dirait « en recul » presque tous les lundis). `regle_num` lit une règle avec défaut, `effort_seance` rend la jauge volume + 20 kg/min de cardio — et filtre elle-même sur `auth.uid()` : SECURITY DEFINER contourne RLS, sans ce filtre une session lisait le volume d'une autre en devinant un uuid de séance (trou trouvé en relecture adverse, bouché et re-mesuré : 0 au lieu de la vraie valeur)", preuve: { sonde: "appelées par les quatre widget_* — ' + S + '", reponse: "debut = lundi 00:00 Paris (2026-08-30T22:00Z), precedent borné au même instant sept jours plus tôt" } },
  // ── L'OBJECTIF HEBDOMADAIRE (05-09) — la seule donnée que l'app ÉCRIT ────
  { id: "b-tb-user-prefs", genre: "table", nom: "user_prefs", titre: "user_prefs", page: "widgets", domaine: "widgets", etat: "ok", quoi: "Une ligne par compte, une préférence : `objectif_hebdo` (borne 1..14 en base — la vitrine propose 3 à 10, et ce choix de design peut bouger sans migration). RLS « own » en select, insert et update. Elle NE va pas dans `reward_rules` : cette table porte les règles du JEU, les mêmes pour tout le monde ; une préférence est autre chose", note: "ÉCRITE PAR L'APP depuis le 13-09 (definir_objectif via ChambreServeur.swift). posée et mesurée ; aucun Swift ne l\'écrit encore. L\'onboarding la posera plus tard", preuve: { sonde: "definir_objectif(7) depuis l'app au banc, puis select user_prefs — 13-09 ~12:00 Paris", reponse: "user_prefs → user_id be69f505-…, objectif_hebdo 7 · effacée ensuite" } },
  { id: "b-fn-definir-objectif", genre: "fonction", nom: "definir_objectif · objectif_hebdo", titre: "definir_objectif(n) et objectif_hebdo()", page: "widgets", domaine: "widgets", etat: "ok", cout: "1 h", quoi: "Écrire et lire l\'objectif. L\'écriture est idempotente par construction (`on conflict do update`) et rend le nouvel état — l\'appelante vient d\'écrire, elle ne doit pas re-demander. Un objectif hors bornes est une erreur MÉTIER : 200 avec un motif, jamais un 500. La lecture retombe sur le défaut de `reward_rules` quand rien n\'a été choisi", note: "BRANCHÉES le 13-09 (ChambreServeur.swift, ChambreEtat.choisir / lireObjectif) : lue à l'ouverture de la chambre Regularity, écrite au choix ; un choix sans session attend localement (« en attente ») et part à la prochaine ouverture connectée. `widget_regularite` rend désormais `objectif` et `reste` (null en fenêtre Mois : l\'objectif est hebdomadaire)", preuve: { sonde: "L'app au banc (-sessionBanc -chambreLongue regularite -chambreObjectif 7), journal [chambre-serveur], puis select user_prefs — 13-09 ~12:00 Paris", reponse: "objectif_hebdo() → 5 · definir_objectif(7) → 7 · select user_prefs du compte de test → objectif_hebdo 7 · au lancement suivant l'app relit 7 (héros « 8 / 7 séances », capture) · ligne effacée ensuite" } },
  { id: "b-rg-objectif-defaut", genre: "regle", nom: "objectif_hebdo_defaut", titre: "objectif_hebdo_defaut", page: "widgets", domaine: "widgets", etat: "srv", reference: true, valeur: "5", quoi: "L\'objectif de qui n\'a jamais choisi. C\'est une règle du jeu (donc `reward_rules`), là où le choix personnel vit dans `user_prefs` — une ligne à changer le jour où l\'onboarding en proposera un autre", preuve: { sonde: "objectif_hebdo() sans préférence — ' + S + '", reponse: "5" } },
  // ── LA LOI DU VIDE, côté serveur (13-09) ───────────────────────────────
  { id: "b-fn-widgets-vide", genre: "fonction", nom: "widget_* — le vide rend des zéros", titre: "widget_* : le vide rend des zéros, jamais un null", page: "widgets", domaine: "widgets", etat: "srv", reference: true, quoi: "La moitié serveur de la loi du vide (b-ux-chambre-vide) : une fenêtre sans séance rend `{faites 0, precedent 0, delta 0, jours []…}`, `{volume 0, exercices [], jours []…}`, `{pic 0, efforts 0, seances []…}`, `{pics [], ascension [], records_battus 0}` — des valeurs que l'écran peut dessiner telles quelles, en gris. Un null obligerait chaque chambre à un chemin spécial, et c'est là que naissent les « rien à afficher »", note: "mesuré sur fenêtre vide le 05-09 (widget_regularite sans séance → faites 0, reste = objectif) ; l'écran ne l'appelle pas encore", preuve: { fichier: "supabase/migrations/20260905090000_widgets_lecture.sql", lignes: "31-32" } },
]
